config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :juniors, param: :name
end

app/models/junior.rb
class Junior < ApplicationRecord
  has_many :acces_juniors, dependent: :destroy
  has_many :users, through: :acces_juniors
end

app/controllers/juniors_controller.rb
class JuniorsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]

  def index
    @juniors = policy_scope(Junior)
  end

  def show
    @junior = Junior.find_by(name: params[:name])
    authorize @junior
  end

  def new
    @junior = Junior.new
    authorize @junior
  end

  def create
    @junior = Junior.new(junior_params)
    new_junior_user
    if @junior.save
      new_acces_junior
      flash[:success] = "Junior successfully created"
      redirect_to @junior
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  private

  def junior_params
    params.require(:junior).permit(:name)
  end

  def new_junior_user
    @user = User.new(
      email: "#{@junior.name.delete(' ').downcase}@jestion.fr",
      first_name: 'admin',
      last_name: @junior.name,
      password: 'adminadmin'
    )
  end

  def new_acces_junior
    @user.save!
    @junior_acces = AccesJunior.new(user_id: @user.id, junior_id: @junior.id, perm_id: Perm.create)
    @junior_acces.save
  end
end

app/views/juniors/index.html.erb
<ul>
    <% @juniors.each do |junior| %>
        <li>
            <%= link_to junior_path(junior.name) do %>
                name : <%= junior.name %>
            <% end %>
        </li>
    <% end %>
</ul>

<% if user_signed_in? %>
    <% if current_user.admin? %>

        <%= link_to new_junior_path do %>
            créer une junior
        <% end %>

    <% end %>
<% end %>

app/views/juniors/new.html.erb
<div class="container">
  <%= simple_form_for(@junior) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/juniors/show.html.erb
<br><br>
Informations
<ul>
    <li>nom : <%= @junior.name %></li>
    <li>alpha : <%= @junior.alpha %></li>
    <li>beta : <%= @junior.beta %></li>
</ul>

<br><br>

utilisateurs
<ul>
    <li>Total : <% @junior.users.each do |user| %> <%= user.first_name %>, <% end %></li>
    <li>Admin : </li>
    <li>Membre :</li>
    <li>Adhérents :</li>
    <li>Clients : </li>
</ul>

<br><br>
liens d'invitation à la structure
<ul>
    <li>Client : <%= link_to 'inviter un membre', new_user_registration_path(registration_data: {type: 'client', junior_id: @junior.id} ) %> </li>
    <li>Adhérent : <%= link_to 'inviter un membre', new_user_registration_path(registration_data: {type: 'adherent', junior_id: @junior.id} ) %> </li>
    <li>Membre : <%= link_to 'inviter un membre', new_user_registration_path(registration_data: {type: 'membre', junior_id: @junior.id} ) %> </li>
</ul>